Repository cacaocoffee/OSS, pull requests merged in 2021-11, with the labels that each got.

#6 Min
  .gitignore
  Server/README.md
  Server/config.js
  Server/dbConn.js
  Server/security.js
  app.js
  bin/www
  package.json
  routes/install.js
  views/install.ejs
Labels: enhancement, back-end

#8 로그인과회원가입 페이지 추가
  public/images/bg.jpg
  public/stylesheets/sign.css
  public/stylesheets/style_1.css
  routes/index.js
  views/login.ejs
  views/sign_up.ejs
Labels: front-end

#13 Database 테이블 추가중
  Server/dbConn.js
  Server/security.js
  controller/api/api.auth.js
  controller/controller.auth.js
  controller/controller.install.js
  package-lock.json
  package.json
  routes/index.js
  routes/install.js
  routes/users.js
  views/index.ejs
  views/sign_up.ejs
Labels: back-end

#15 lang 삭제 user 테이블 생성
  controller/controller.install.js
Labels: back-end, database

#17 Session 추가 및 config 파일 구조 변경
  Server/config.js
  Server/dbConn.js
  app.js
  controller/api/api.auth.js
  controller/controller.auth.js
  controller/controller.install.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  views/index.ejs
  views/login.ejs
Labels: back-end, database

#18 hotfix: 심각한 실행 중단 문제 수정
  Server/config.js
  Server/dbConn.js
  Server/tools.js
  app.js
  controller/controller.auth.js
  controller/controller.install.js
  routes/index.js
  routes/users.js
Labels: bug, back-end

#19 language_user language_list 테이블 추가
  controller/controller.install.js
Labels: back-end, database

#24 Install 관련 버그 수정
  controller/controller.install.js
Labels: bug, enhancement, back-end

#22 todo table 생성
  controller/api/api.search.js
  controller/controller.install.js
  controller/controller.profile.js
  routes/index.js
Labels: back-end, database

#29 todo 테이블에 대한 api 작성
  controller/api/api.search.js
Labels: back-end, database

#28 project 탐색 api 추가
  controller/api/api.search.js
Labels: back-end, database

#30 Front
  public/images/background.jpg
  public/stylesheets/glass.css
  public/stylesheets/profile.css
  public/stylesheets/project.css
  public/stylesheets/project_main.css
  routes/index.js
  routes/users.js
  views/common/header.ejs
  views/common/preHeader.ejs
  views/install.ejs
  views/language_list.ejs
  views/layout.ejs
  views/navigation.ejs
  views/profile.ejs
  views/project.ejs
  views/project_main.ejs
  views/sign_up.ejs
Labels: front-end

#31 todo list에 있는 do -> done
  controller/api/api.search.js
  controller/controller.install.js
Labels: back-end, database

#32 project 테이블에서 language 부분 분리 lang_proj 테이블 생성 및 api 수정
  controller/api/api.search.js
  controller/controller.install.js
Labels: back-end, database

#33 Front profile project 페이지 틀 완성
  public/images/bg.jpg
  public/images/constellations-g24af394ca_1920.jpg
  public/stylesheets/language.css
  public/stylesheets/login.css
  public/stylesheets/navi.css
  public/stylesheets/project.css
  public/stylesheets/project_main.css
  public/stylesheets/sign.css
  routes/index.js
  views/index.ejs
  views/language_list.ejs
  views/login.ejs
  views/main_file/language_list.ejs
  views/profile.ejs
  views/project.ejs
  views/project_main.ejs
  views/sign_up.ejs
Labels: front-end

#34 project 정보전달 api 작성
  controller/api/api.search.js
Labels: back-end, database

#40 todo/ todo user 테이블 api 수정
  controller/api/api.search.js
  controller/controller.install.js
Labels: back-end, database

#42 Front index
  jquery.min_1.12.4.js
  package-lock.json
  public/stylesheets/1glass.css
  public/stylesheets/glass1.css
  public/stylesheets/profile.css
  public/stylesheets/profile1.css
  public/stylesheets/reset.css
  public/stylesheets/style.css
  views/common/header.ejs
  views/common/preHeader.ejs
  views/content.ejs
  views/index.ejs
  views/nav.ejs
  views/profile1.ejs
  views/profile2.ejs
  views/project_main.ejs
Labels: front-end

#43 front-back 1차 통합
  Server/config.js
  app.js
  controller/api/api.auth.js
  controller/api/api.common.js
  controller/api/api.search.js
  controller/controller.api.js
  controller/controller.auth.js
  controller/controller.index.js
  controller/controller.install.js
  controller/controller.profile.js
  controller/controller.project.js
  controller/controller.user.js
  public/script.js
  public/stylesheets/common.css
  public/stylesheets/form.css
  public/stylesheets/glass.css
  public/stylesheets/glass1.css
  public/stylesheets/header.css
  public/stylesheets/index.css
  public/stylesheets/login.css
  public/stylesheets/nav.css
  public/stylesheets/profile.css
  public/stylesheets/project.css
  public/stylesheets/project_detail.css
  public/stylesheets/sign.css
  routes/_routerCtrl.js
  routes/api.js
  routes/error.js
  routes/index.js
  routes/project.js
  routes/users.js
  views/common/header.ejs
  views/common/preHeader.ejs
  views/content.ejs
  views/content/index.ejs
  views/content/profile.ejs
  views/content/project.ejs
  views/content/project_detail.ejs
  views/index.ejs
  views/install.ejs
  views/layout.ejs
  views/login.ejs
  views/sign_up.ejs
  views/signup.ejs
Labels: front-end, back-end, database

#44 project 팀장, 생성 시간 column 추가
  controller/api/api.search.js
  controller/controller.install.js
Labels: back-end, database

#49 front-back 3차 통합
  Server/dbConn.js
  controller/api/api.search.js
  controller/controller.api.js
  controller/controller.todo.js
  public/stylesheets/checkbox.css
  public/stylesheets/form.css
  public/stylesheets/glass1.css
  public/stylesheets/pagenation.css
  public/stylesheets/reset.css
  public/stylesheets/scrollbar.css
  public/stylesheets/style.css
  public/stylesheets/todo.css
  routes/_routerCtrl.js
  routes/api.js
  routes/index.js
  routes/todo.js
  views/common/header.ejs
  views/content/profile.ejs
  views/content/project.ejs
  views/content/todo.ejs
  views/profile1.ejs
  views/profile2.ejs
  views/project_edit.ejs
Labels: front-end, back-end, database

#50 userinfo 수정
  controller/api/api.auth.js
  controller/api/api.search.js
Labels: bug, back-end
